title: JSH
description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs

url: https://jsh1011.github.io/

aux_links:
  Template Repository: https://github.com/JSH1011
